# Generated by Django 5.1.3 on 2024-11-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVAR', 'Ativado'), ('DELETADO', 'Deletado'), ('ESPERAR_APROVACAO', 'Esperar Aprovação')], default='ativado', max_length=50),
        ),
    ]
