# Generated by Django 5.1.3 on 2024-11-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DELETADO', 'Deletado'), ('RASCUNHO', 'Rascunho'), ('ESPERAR_APROVACAO', 'Esperar Aprovação'), ('ATIVAR', 'Ativado')], default='ativado', max_length=50),
        ),
    ]
