# Generated by Django 5.1.3 on 2024-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_product_thumbnail_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DELETADO', 'Deletado'), ('ATIVAR', 'Ativado'), ('RASCUNHO', 'Rascunho'), ('ESPERAR_APROVACAO', 'Esperar Aprovação')], default='Ativado', max_length=50),
        ),
    ]
