# Generated by Django 5.1.3 on 2024-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0019_rename_merc_id_order_pagamento_intent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pagamento_intent',
            new_name='payment_intent',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DELETADO', 'Deletado'), ('ATIVAR', 'Ativado'), ('RASCUNHO', 'Rascunho'), ('ESPERAR_APROVACAO', 'Esperar Aprovação')], default='Ativado', max_length=50),
        ),
    ]
