# Generated by Django 5.1.3 on 2024-11-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userfrofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfrofile',
            name='is_vender',
            field=models.BooleanField(default=False),
        ),
    ]
